import streamlit as st
import requests
import pandas as pd
import json

from utils.api import REPORTS_URL

st.set_page_config(
    page_title="Report History",
    page_icon="📚",
    layout="wide"
)

st.title("📋 Medical Report History")

st.caption(
    "View, search and review previously analyzed clinical reports generated by MedAI."
)

st.write("")

# ==========================================================
# Load Reports
# ==========================================================

try:

    response = requests.get(
        REPORTS_URL,
        timeout=10
    )

    if response.status_code != 200:
        st.error(
            f"Backend returned {response.status_code}"
        )
        st.stop()

    reports = response.json()

except Exception as e:

    st.error(f"Unable to connect to backend.\n\n{e}")
    st.stop()

if not reports:
    st.info("No reports available.")
    st.stop()

# ==========================================================
# Build DataFrame
# ==========================================================

data = []

for report in reports:

    try:

        # Safety:
        # Some APIs may return JSON strings instead of dicts

        if isinstance(report, str):
            report = json.loads(report)

        analysis = report.get("analysis", {})

        if isinstance(analysis, str):
            analysis = json.loads(analysis)

        score = analysis.get("health_score", "-")

        patient = report.get("patient_name", "Unknown")

        if not patient or patient.strip() == "":
            patient = "Unknown Patient"

        if patient.strip().lower() == "unknown":
            patient = "Unknown Patient"

        data.append({

            "Report ID": report.get("id"),

            "Patient Name": patient,

            "Document Type": report.get(
                "document_type",
                "Unknown"
            ),

            "Health Score": score

        })

    except Exception:

        # Skip bad records instead of crashing
        continue

df = pd.DataFrame(data)

if df.empty:
    st.warning("No valid reports found.")
    st.stop()

# ==========================================================
# Dashboard Metrics
# ==========================================================

total_reports = len(df)

prescriptions = len(
    df[df["Document Type"] == "Prescription"]
)

lab_reports = len(
    df[df["Document Type"] == "Lab Report"]
)

scores = pd.to_numeric(
    df["Health Score"],
    errors="coerce"
)

average_score = (
    round(scores.mean(), 1)
    if not scores.empty
    else 0
)

c1, c2, c3, c4 = st.columns(4)

c1.metric("📄 Total Reports", total_reports)

c2.metric("💊 Prescriptions", prescriptions)

c3.metric("🧪 Lab Reports", lab_reports)

c4.metric("❤️ Avg Health Score", average_score)

st.divider()

# ==========================================================
# Search
# ==========================================================

search = st.text_input(
    "🔍 Search by Patient Name"
)

if search:

    df = df[
        df["Patient Name"].str.contains(
            search,
            case=False,
            na=False
        )
    ]

# ==========================================================
# Filter
# ==========================================================

document_filter = st.selectbox(
    "Filter by Document Type",
    [
        "All",
        "Prescription",
        "Lab Report"
    ]
)

if document_filter != "All":

    df = df[
        df["Document Type"] == document_filter
    ]

# ==========================================================
# Display Table
# ==========================================================

st.dataframe(
    df,
    use_container_width=True,
    hide_index=True
)

st.success(
    f"Showing {len(df)} clinical report(s)."
)